export const servicesData: Record<string, { homeData: any[]; smeData: any[] }> =
  {
    aba: {
      homeData: [
        {
          name: "Home Delight",
          price: 20000,
          speed: "Up to 10Mbps",
          minSpeed: "1Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Delight Plus",
          price: 35000,
          speed: "Up to 15Mbps",
          minSpeed: "2Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Extreme",
          price: 50000,
          speed: "Up to 20Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
      smeData: [
        {
          name: "SME Premium",
          price: 60000,
          speed: "Up to 30Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Starter",
          price: 95000,
          speed: "Up to 40Mbps",
          minSpeed: "5Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Premium",
          price: 130000,
          speed: "Up to 50Mbps",
          minSpeed: "7Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
    },
    lagos: {
      homeData: [
        {
          name: "Home Delight",
          price: 20000,
          speed: "Up to 10Mbps",
          minSpeed: "1Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Delight Plus",
          price: 35000,
          speed: "Up to 15Mbps",
          minSpeed: "2Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Extreme",
          price: 50000,
          speed: "Up to 20Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
      smeData: [
        {
          name: "SME Premium",
          price: 60000,
          speed: "Up to 30Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Starter",
          price: 95000,
          speed: "Up to 40Mbps",
          minSpeed: "5Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Premium",
          price: 130000,
          speed: "Up to 50Mbps",
          minSpeed: "7Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
    },
    enugu: {
      homeData: [
        {
          name: "Home Delight",
          price: 20000,
          speed: "Up to 10Mbps",
          minSpeed: "1Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Delight Plus",
          price: 35000,
          speed: "Up to 15Mbps",
          minSpeed: "2Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Extreme",
          price: 50000,
          speed: "Up to 20Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
      smeData: [
        {
          name: "SME Premium",
          price: 60000,
          speed: "Up to 30Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Starter",
          price: 95000,
          speed: "Up to 40Mbps",
          minSpeed: "5Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Premium",
          price: 130000,
          speed: "Up to 50Mbps",
          minSpeed: "7Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
    },
    ibadan: {
      homeData: [
        {
          name: "Home Delight",
          price: 20000,
          speed: "Up to 10Mbps",
          minSpeed: "1Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Delight Plus",
          price: 35000,
          speed: "Up to 15Mbps",
          minSpeed: "2Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Extreme",
          price: 50000,
          speed: "Up to 20Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
      smeData: [
        {
          name: "SME Premium",
          price: 60000,
          speed: "Up to 30Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Starter",
          price: 95000,
          speed: "Up to 40Mbps",
          minSpeed: "5Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Premium",
          price: 130000,
          speed: "Up to 50Mbps",
          minSpeed: "7Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
    },
    onitsha: {
      homeData: [
        {
          name: "Home Delight",
          price: 20000,
          speed: "Up to 10Mbps",
          minSpeed: "1Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Delight Plus",
          price: 35000,
          speed: "Up to 15Mbps",
          minSpeed: "2Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Extreme",
          price: 50000,
          speed: "Up to 20Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
      smeData: [
        {
          name: "SME Premium",
          price: 60000,
          speed: "Up to 30Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Starter",
          price: 95000,
          speed: "Up to 40Mbps",
          minSpeed: "5Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Premium",
          price: 130000,
          speed: "Up to 50Mbps",
          minSpeed: "7Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
    },
    calabar: {
      homeData: [
        {
          name: "Home Delight",
          price: 20000,
          speed: "Up to 10Mbps",
          minSpeed: "1Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Delight Plus",
          price: 35000,
          speed: "Up to 15Mbps",
          minSpeed: "2Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "Home Extreme",
          price: 50000,
          speed: "Up to 20Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 90000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
      smeData: [
        {
          name: "SME Premium",
          price: 60000,
          speed: "Up to 30Mbps",
          minSpeed: "3Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Starter",
          price: 95000,
          speed: "Up to 40Mbps",
          minSpeed: "5Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
        {
          name: "SME Premium",
          price: 130000,
          speed: "Up to 50Mbps",
          minSpeed: "7Mbps",
          validity: "30 days",
          setupCost: 100000,
          conditions: "Subject to site survey",
          vatIncluded: true,
        },
      ],
    },
  };
